import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import PageLayout from "./page-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Booking App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <PageLayout>{children}</PageLayout>
                    <App
                </Providers>
            </body>
        </html>
    );
}
